---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: trixie
    groups:
      - family_debian
    children:
      - debian
    box: bento/debian-13
    memory: 1024
    cpus: 1
    provider_options:
      gui: false
  - name: bookworm
    groups:
      - family_debian
    children:
      - debian
    box: bento/debian-12
    memory: 1024
    cpus: 1
    provider_options:
      gui: false
provisioner:
  name: ansible
  options:
    diff: true
  config_options:
    defaults:
      hash_behaviour: merge
      remote_tmp: /tmp
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
# verifier:
#   name: ansible
# scenario:
#   test_sequence:
#     - dependency
#     - cleanup
#     - destroy
#     - syntax
#     - create
#     - prepare
#     - converge
#     - idempotence
#     - side_effect
#     - verify
#     - cleanup
#     - destroy
#   create_sequence:
#     - dependency
#     - create
#     - prepare
#   check_sequence:
#     - dependency
#     - cleanup
#     - destroy
#     - create
#     - prepare
#     - converge
#     - check
#     - destroy
#   converge_sequence:
#     - dependency
#     - create
#     - prepare
#     - converge
#   destroy_sequence:
#     - dependency
#     - cleanup
#     - destroy
